{% set name = "backports.weakref" %}
{% set version = "1.0rc1" %}
{% set sha256 = "8813bf712a66b3d8b85dc289e1104ed220f1878cf981e2fe756dfaabe9a82892" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - backports
  run:
    - python
    - backports

test:
  imports:
    - backports.weakref

about:
  home: https://github.com/pjdelport/backports.weakref
  license: Python-2.0
  summary: 'Backport of new features in Python''s weakref module'
  dev_url: https://github.com/pjdelport/backports.weakref

extra:
  recipe-maintainers:
    - adrianchia
